# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15lOEkbfDB3FLQ1MxYogqMQnjrsyS0BYs
"""

import sys 
 from time import sleep 
 LED_PATH = "/sys / class / gpio / gpio"+ LED_NUMBER + " /" 
 SYSFS_DIR = "/ sys / class / gpio /" 
 LED_NUMBER = "20" 

 def writeLED ( filename , value , path = LED_PATH ): 

	fo = open ( path + filename ,"w") 
	fo . write ( value ) 
 	fo . close () 
 	return 



for i in range (5):
  writeLed(filename = "export", value = "20", path = SYSFS_DIR) #export: habilita a entrada/saida 20
  sleep (0.1) #para garintir que foi exportada
  writeLED ( filename =" direction ", value =" out ") #configurando como saída
  writeLed(filename = "value", value = "1") #value = 1: liga o LED da saída 20
  sleep(2) #espera 2 segundos
  writeLed(filename = "value", value = "0") #value = 0: desliga o LED da saída 20

  LED_NUMBER = "21"
  LED_PATH = "/sys / class / gpio / gpio"+ LED_NUMBER + " /"
  writeLed(filename = "export", value = "21", path = SYSFS_DIR) #export: habilita a entrada/saida 21
  sleep (0.1) #para garintir que foi exportada
  writeLED ( filename =" direction ", value =" out ") #configurando como saída
  writeLed(filename = "value", value = "1") #value = 1: liga o LED da saída 21
  sleep(1) #espera 1 segundo
  writeLed(filename = "value", value = "0") #value = 0: desliga o LED da saída 21

  LED_NUMBER = "16"
  LED_PATH = "/sys / class / gpio / gpio"+ LED_NUMBER + " /"
  writeLed(filename = "export", value = "16", path = SYSFS_DIR) #export: habilita a entrada/saida 16
  sleep (0.1) #para garintir que foi exportada
  writeLED ( filename =" direction ", value =" out ") #configurando como saída
  writeLed(filename = "value", value = "1") #value = 1: liga o LED da saída 16
  sleep(1) #espera 1 segundo
  writeLed(filename = "value", value = "0") #value = 0: desliga o LED da saída 16